ML = \
     core.ml \
     mode.ml \

# install rules

install: ml-install

ml-install:
	for f in $(ML) ; do install --mode 0644 -D ml/$$f $(SHAREDIR)/amp/$$f ; done

# run rules

run: install
	$(MAKE) run -C ..

debug: install
	$(MAKE) debug -C ..
