# install rules

install: ml-install

ml-install:
	install --mode 0644 -D ml/core.ml $(SHAREDIR)/amp/core.ml

# run rules

run: install
	$(MAKE) run -C ../sin

debug: install
	$(MAKE) debug -C ../sin
